# Generated by Django 5.1.2 on 2024-10-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0002_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_model',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
    ]
