# Generated by Django 5.1.2 on 2024-10-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0003_image_model_is_annotated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_model',
            name='is_annotated',
        ),
    ]
