# Generated by Django 5.1.2 on 2024-10-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0004_remove_image_model_is_annotated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('x1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
            ],
        ),
    ]
